# Site settings
title: Andy Zhang
description: I'll make sure to come up with something more descriptive to put here in 2009.
url: "http://andy.zhang.me"
baseurl: ""
intro: I live and work in Shenzhen, spending most of my days at <a href="https://oneplus.net/">OnePlus</a> HQ. When time allows, I make internet things and <a href="http://andyzhang.com/">shoot photos</a>.
twitter_url: "https://twitter.com/yesokayawesome"
linkedin_url: "https://www.linkedin.com/in/andyzhang"
500px_url: "https://500px.com/a-z"
photos_url: "http://andyzhang.com"

# Build settings
permalink: pretty
markdown: kramdown
gems:
  - jekyll-sitemap
