# Site settings
title: Andy Zhang
description: I'll make sure to come up with something more descriptive to put here in 2017.
url: "http://andy.zhang.me"
baseurl: ""
twitter_url: "https://twitter.com/yesokayawesome"
linkedin_url: "https://www.linkedin.com/in/andyzhang"
500px_url: "https://500px.com/a-z"
photos_url: "http://andyzhang.com"
intro: I work on internet things and <a href="https://500px.com/a-z">shoot photos</a>. Currently involved with getting <a href="#">Parkour</a> (not the sport) off the ground.

# Build settings
permalink: pretty
markdown: kramdown
gems:
  - jekyll-sitemap
